title: kubeless 
project_name: kubeless
description: >
  A Kubernetes Native Serverless Framework. Kubeless supports both HTTP and event based triggers, has a serverless plugin, a graphical user interface and multiple runtimes, including Python and Node.js.
repository_url: https://github.com/kubeless/kubeless
repository_shorthand: kubeless/kubeless

author_name: The Kubeless Authors
author_url: https://github.com/kubeless

markdown: kramdown

gems:
  - jekyll-seo-tag
